

const data = {
    cardData:[
        {
            id:1,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:2,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:3,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:4,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:5,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:6,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:7,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:8,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:9,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:10,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:11,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:12,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:13,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:14,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:15,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:16,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:17,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:18,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:19,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:20,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
        {
            id:21,
            img:'assets/Images/main-clients-haver-img-1.png',
        },
    ]
  
}

export default data;